### ISSUE TITLE
HTAPP | Outstanding release 2 manifests

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/data-release-tracker#252]
Biospecimen, Clinical, and Single Cell Level 1 & 2 data/metadata are slated for release 2 according to the HTAPP [release schedule](https://docs.google.com/spreadsheets/d/1S-_eXXUV00Dgi1axLy6voAR7dQ6MkPxvmfQuiXDmxPw/edit#gid=454860857); however, a number of these manifests have yet to be submitted to Synapse (users encountered app errors at time of submission).

Manifests can be found here: https://drive.google.com/drive/folders/1vxF03IsnPWiTJyrwEENhfKGKxrXetLOu

**Comment by clarisse-lau** [comment]
Thanks for submitting all release 2 manifests, @elv-sb!

**Comment by vthorsson** [comment]
Hooray @elv-sb @clarisse-lau @adamjtaylor !
